selected_level = 0
selected_world = 0
active = false
alarm[0] = 30
global.leveltorestart = -4

world_array[0] = "TOWER REALM"
world_array[1] = "COSMIC WEST"
world_array[2] = "NO VACATION CRUISE"
world_array[3] = "21ST CENTURY EMPIRE"
world_array[4] = "TERROR NATION"
world_array[5] = "EXTRA"
world_array[6] = "EXIT"

level_array[0][0] = ["JOHN GUTTER", entrance_1, "entrance"]
level_array[0][1] = ["PIZZASCAPE", medieval_1, "medieval"]
level_array[0][2] = ["ANCIENT CHEESE", ruin_1, "ruin"]
level_array[0][3] = ["BLOODSAUCE DUNGEON", dungeon_1, "dungeon"]
level_array[0][4] = ["HUB", tower_entrancehall, "tower"]
level_array[0][5] = ["TUTORIAL NEW", tutorial_1, "tutorial"]
level_array[0][5] = ["OLD DRAGON LAIR", dragonlair_1, "dragonlair"]
level_array[1][0] = ["OREGANO DESERT", badland_1, "badland"]
level_array[1][1] = ["WASTEYARD", graveyard_1, "graveyard"]
level_array[1][2] = ["FUN FARM", farm_1, "farm"]
level_array[1][3] = ["FASTFOOD SALOON", saloon_1, "saloon"]
level_array[2][0] = ["CRUST COVE", plage_entrance, "plage"]
level_array[2][1] = ["GNOME FOREST", forest_1, "forest"]
level_array[2][2] = ["DEEP DISH 9", space_1, "space"]
level_array[2][3] = ["GOLF", minigolf_1, "minigolf"]
level_array[3][0] = ["THE PIG CITY", street_intro, "street"]
level_array[3][1] = ["OH SHIT", sewer_1, "sewer"]
level_array[3][2] = ["PEPPIBOT FACTORY", industrial_1, "industrial"]
level_array[3][3] = ["RREFRIDGERATOR REFERIDGERADOR FREEZERATOR", freezer_1, "freezer"]
level_array[4][0] = ["PIZZASCARE", chateau_1, "chateau"]
level_array[4][1] = ["PEPPERS MANSION", mansion_3, "mansion"]
level_array[4][2] = ["DONT MAKE A SOUND", kidsparty_1, "kidsparty"]
level_array[4][3] = ["WAR", war_1, "war"]
level_array[5][0] = ["BATHROOM", bathroom_1, "bathroom"]
level_array[5][1] = ["FACTORY REMIX", factory_1_REMIX, "factoryremix"]
level_array[5][2] = ["THE ANCIENT TOWER", ancient_1, "ancient"]
level_array[5][3] = ["OUTSIDE TEST", Titlescreen, "titlescreen"]
level_array[5][4] = ["GREMLINS STRONGCOLD", cold1, "strongcold"]
level_array[5][5] = ["REALLY BAD DONT PLAY RN", arctic_1, "arctic"]
level_array[6][0] = ["THE CRUMBLING TOWER OF PIZZA", tower_finalhallway, "tower"]

toppin_info[0] = [0, spr_toppinshroom] // image_index, sprite
toppin_info[1] = [0, spr_toppincheese]
toppin_info[2] = [0, spr_toppintomato]
toppin_info[3] = [0, spr_toppinsausage]
toppin_info[4] = [0, spr_toppinpineapple]

stickpressed = false
key_up2 = false
key_down2 = false
key_left2 = false
key_right2 = false
key_jump2 = false
